In [1]:
import numpy as np

# Input data: X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

print("Original X:\n", X)
print("Original y:\n", y)

# Scale input data
X = X / np.amax(X, axis=0)  # Scale X based on maximum values per feature
y = y / 100  # Scale y as max test score is 100

print("\nScaled X:\n", X)
print("Scaled y:\n", y)

class Neural_Network:
    def __init__(self):
        # Network parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        # Initialize weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)  # Weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)  # Weight matrix from hidden to output layer

    def forward(self, X):
        # Forward propagation
        self.z = np.dot(X, self.W1)          # Dot product of input and first layer weights
        self.z2 = self.sigmoid(self.z)       # Activation function on hidden layer
        self.z3 = np.dot(self.z2, self.W2)   # Dot product of hidden layer and second layer weights
        o = self.sigmoid(self.z3)            # Final activation function
        return o

    def sigmoid(self, s):
        # Activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        # Derivative of sigmoid function
        return s * (1 - s)

    def backward(self, X, y, o):
        # Backpropagation
        self.o_error = y - o                       # Error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o)  # Applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T)  # z2 error: contribution of hidden layer weights to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)  # Applying derivative to z2 error

        # Adjust weights
        self.W1 += X.T.dot(self.z2_delta)  # Adjust input to hidden weights
        self.W2 += self.z2.T.dot(self.o_delta)  # Adjust hidden to output weights

    def train(self, X, y):
        # Train the network
        o = self.forward(X)
        self.backward(X, y, o)

# Instantiate and train the Neural Network
NN = Neural_Network()
for i in range(1000):  # Training for 1,000 epochs
    print("Input:\n", X)
    print("Actual Output:\n", y)
    print("Predicted Output:\n", NN.forward(X))
    print("Loss:\n", np.mean(np.square(y - NN.forward(X))))  # Mean squared loss
    print("\n")
    NN.train(X, y)


Original X:
 [[2. 9.]
 [1. 5.]
 [3. 6.]]
Original y:
 [[92.]
 [86.]
 [89.]]

Scaled X:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Scaled y:
 [[0.92]
 [0.86]
 [0.89]]
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.62550793]
 [0.57114984]
 [0.65773334]]
Loss:
 0.0747026002198805


Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.66301798]
 [0.60573272]
 [0.69575689]]
Loss:
 0.05614066474928763


Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.69334563]
 [0.6341115 ]
 [0.72574486]]
Loss:
 0.043125857086042836


Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.7180