In [1]:
import numpy as np

# Input data: X = (inputs), Y = (expected output)
X = np.array(([0, 0], [0, 1], [1, 0], [1, 1]), dtype=float)
Y = np.array(([0], [1], [1], [1]), dtype=float)

print('Value X ->', X)
print('Value Y ->', Y)
print('X Shape (rows, columns) ->', X.shape)
print('Y Shape (rows, columns) ->', Y.shape)

class NeuralNetwork:
    def __init__(self):
        self.input_size = 2
        self.output_size = 1
        self.hidden_size = 2

        # Initialize weights and biases
        self.w1 = np.array([[0.6, -0.3], [-0.1, 0.4]])  # Input to hidden layer weights
        self.b1 = np.array([[0.3, 0.5]])                # Bias for hidden layer
        self.w2 = np.array([[0.4], [0.1]])              # Hidden to output layer weights
        self.b2 = np.array([[-0.2]])                    # Bias for output layer
        self.lr = 0.25                                  # Learning rate

    def forward(self, X):
        # Forward propagation
        self.z = np.dot(X, self.w1) + self.b1
        print('Value of Z ->\n', self.z)
        print('-----------------------')

        self.z2 = self.sigmoid(self.z)
        print('Value of Z2 ->\n', self.z2)
        print('-----------------------')

        self.z3 = np.dot(self.z2, self.w2) + self.b2
        print('Value of Z3 ->\n', self.z3)
        print('-----------------------')

        o = self.sigmoid(self.z3)
        print('Value of O ->\n', o)
        print("-----FORWARD OVER------")
        print('-----------------------\n\n')
        return o

    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))

    def sigmoid_prime(self, s):
        return s * (1 - s)

    def backward(self, X, y, o):
        # Backward propagation
        self.o_error = y - o  # Calculate output error
        print('Value of O Error ->\n', self.o_error)
        print('-----------------------')

        self.o_delta = self.o_error * self.sigmoid_prime(o)  # Error x Derivative
        print('Value of O Delta ->\n', self.o_delta)
        print('-----------------------')

        self.z2_error = self.o_delta.dot(self.w2.T)  # Hidden layer error
        print('Value of Z2 Error ->\n', self.z2_error)
        print('-----------------------')

        self.z2_delta = self.z2_error * self.sigmoid_prime(self.z2)  # Apply derivative
        print('Value of Z2 Delta ->\n', self.z2_delta)
        print('-----------------------')

        # Update weights with gradient descent
        self.w1 += X.T.dot(self.z2_delta) * self.lr
        print('Updated W1 ->\n', self.w1)
        print('-----------------------')

        self.w2 += self.z2.T.dot(self.o_delta) * self.lr
        print('Updated W2 ->\n', self.w2)
        print('-----------------------')

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

# Train and evaluate the neural network
nn = NeuralNetwork()
nn.train(X, Y)

print("Input:\n", X)
print('-----------------------')
print("Actual Output:\n", Y)
print('-----------------------')
print("Loss:\n", np.mean(np.square(Y - nn.forward(X))))  # Mean squared loss
print('-----------------------')
print("\n")


Value X -> [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Value Y -> [[0.]
 [1.]
 [1.]
 [1.]]
X Shape (rows, columns) -> (4, 2)
Y Shape (rows, columns) -> (4, 1)
Value of Z ->
 [[0.3 0.5]
 [0.2 0.9]
 [0.9 0.2]
 [0.8 0.6]]
-----------------------
Value of Z2 ->
 [[0.57444252 0.62245933]
 [0.549834   0.7109495 ]
 [0.7109495  0.549834  ]
 [0.68997448 0.64565631]]
-----------------------
Value of Z3 ->
 [[0.09202294]
 [0.09102855]
 [0.1393632 ]
 [0.14055542]]
-----------------------
Value of O ->
 [[0.52298951]
 [0.52274144]
 [0.53478452]
 [0.53508112]]
-----FORWARD OVER------
-----------------------


Value of O Error ->
 [[-0.52298951]
 [ 0.47725856]
 [ 0.46521548]
 [ 0.46491888]]
-----------------------
Value of O Delta ->
 [[-0.13047097]
 [ 0.11906782]
 [ 0.11574098]
 [ 0.11565755]]
-----------------------
Value of Z2 Error ->
 [[-0.05218839 -0.0130471 ]
 [ 0.04762713  0.01190678]
 [ 0.04629639  0.0115741 ]
 [ 0.04626302  0.01156576]]
-----------------------
Value of Z2 Delta ->
 [[-0.01275789 -